[theme]
base                     = "light"
primaryColor             = "#3B82F6"
backgroundColor          = "#ffffff"
secondaryBackgroundColor = "#EFF6FF"
textColor                = "#111111"
font                     = "sans serif"
